version: 2.1
orbs:
  aws-cli: circleci/aws-cli@4.1.2
jobs:
  build_project:
    working_directory: ~/frontend-manage
    docker:
      - image: node:latest
    steps:
      - checkout
      - run:
          name: Installing yarn
          command: yarn
      - run:
          name: Build source
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
  deploy_s3:
    executor: aws-cli/default
    steps:
      - attach_workspace:
          at: .
      - aws-cli/setup:
          profile_name: default
      - run:
          name: Upload file to S3
          command: |
            asw s3 rm s3://shop-manage.xyz/assets --recursive
            aws s3 rb ss3://shop-manage.xyz --force
            aws s3 sync ./dist/ s3://shop-manage.xyz
workflows:
  frontend-manage-pipeline:
    jobs:
      - build_project:
          filters:
            branches:
              only:
                - deployment-circleci
      - hold:
          type: approval
          requires:
            - build_project
          filters:
              branches:
                only:
                  - deployment-circleci
      - deploy_s3:
          context: s3-context
          requires:
            - build_project
            - hold
          filters:
            branches:
              only:
                - deployment-circleci

