# circleci config
# version
version: 2.1
# orbs
orbs:
  node: circleci/node@5.1.1
jobs:
  set-up-node:
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: '18'
      - run: node --version
workflows:
  frontend-manage-pipeline:
    jobs:
      - set-up-node:
          filters:
            branches:
              only:
                - deployment-circleci
